### ISSUE TITLE
download files named as index.php (as script-name) and not the file name

### ISSUE THREAD

**Issue by domsie** [Athlon1600/php-proxy-app#22]
Hi,

i have the problem that the proxy downloads a file named as index.php. 
At first I thought it is because of my Nginx configuration, but then I check the behavior on unblockvideos. com and there is the same behavior. , ,
Is there a fix for this behavior or is it even though a wrong implementation of me?

Example:

https://sf1.unblockvideos.com/index.php?q=m63W05uUkq2u3WGWoZ_SX5uYX8ehp6ef1MSU2JTFZpWXqNnRzdTEmqrFm6aYncelnZycyJGmapKWmWOWnJtpbGGh1tDNpNdzaJppaW5tmGJwbFbZb2NvY5WJo6LGyJlrZmvFxcXHx25pyJdnnWrIlXBoZJhoaXJnypOUlg

**Comment by Athlon1600** [comment]
I'm aware of that problem and the problem is on the php-proxy side. I'll have it fixed by the end of the day.

**Comment by domsie** [comment]
Hi,
thank you for the fast fix :)
I want to detect and scan each file download via sophos savid. Where is the best entry point to analyse the http response to look at the content-disposition and content-type ( if  disposition-type == "attachment") and start a sandbox to scan each file. I still does not know if this is the correct way to check if a response is a file-download - but this is so far my approach.

**Comment by Athlon1600** [comment]
Okay, that first problem is fixed:  
https://github.com/Athlon1600/php-proxy/commit/b24f6e02cecb87ba5fc01911b008579ac138b6f9  
  
You can intercept proxy's connection at any point using plugins. Something like this put inside TestPlugin.php should work:  
```php
	public function onHeadersReceived(ProxyEvent $event){
		$headers= $event['response']->headers->all();
		if($headers->has('your_header')){
				// do something
		}
	}
```

**Comment by domsie** [comment]
Hi :)
Thx for your help and the quick fix; but the behaviour is still triggy. 

===================
CASE A:) 

direct file-download
I want to get following download via php-proxy || unblockvideos.com:
http://dl.cdn.chip.de/downloads/19606782/CarotDAV1.13.0.zip?cid=61866103&platform=chip&1466668408-1466675908-a08a8e-B-012392fa8751258d9e8cf15fdf30586e

When i am use the direct download (and not the javascript function from chip.de to serve the download file) the content-disposition filename is set as => 
filename="CarotDAV1.13.0.zip?cid=61866103&platform=chip&1466668408-1466675908-a08a8e-B-012392fa8751258d9e8cf15fdf30586e="

( i am logging the response-headers)

the filename must be filename="CarotDAV1.13.0.zip"
so i think we must clear/delete the params of the filename before set the content-disposition.

===================
CASE B:)

download via javascript funktionality:

/index.php?q=ydfW1W1iYqlexp3L1ZSWnGOapazIqKJnxaRmdNup0XPJ19bVWGZ0VmKpWpSr3amuYpSfodNkmJ2Gan2Z1a7TotDExthYZXmUYcKZ0dzUnqaVlaqXxKunr8Kgo5ScaJ1sl5SSmmGbp56ciGio2Ytle2VlbW6ZbWRrmmpcZ5ytimmllpiVY1hlZ6OIaKbIm2tnZ2SZnpVrmpmUnZ2YlmubZsTFyMeZaWNmkseZmYvWk56ZfZix0quodc-noKPZq8aizcjU4ZhoYw


then i´ve become an index.php file (gzp encoded) (23kb file-size than the original CarotDAV1.13.0.zip 1461 kb)
the index.php has a "header":

w.chip.de/downloads/c1_downloads_auswahl_61866105.html?t=1466670392&amp;v=3600&amp;s=c59033bf25fa3efc0460cbfbf605bdd7</a></p>HTTP/1.1 200 OK
Server: nginx
Date: Thu, 23 Jun 2016 09:12:54 GMT
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.6.1
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
content-disposition: filename="c1_downloads_auswahl_61866105.html?t=1466670392&v=3600&s=c59033bf25fa3efc0460cbfbf605bdd7"
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
expires: 0
Content-Encoding: gzip

**Comment by Athlon1600** [comment]
Case A is now fixed:
https://github.com/Athlon1600/php-proxy/commit/9d797fc6bb10815be4e8ac34a0dfdf41d6167f6a
