### ISSUE TITLE
 Fatal error: Call to undefined function Proxy\Http\mb_parse_str() 

### ISSUE THREAD

**Issue by desbest** [Athlon1600/php-proxy-app#51]
I've just uploaded php-proxy to my hosting account and I get this error.

Fatal error: Call to undefined function Proxy\Http\mb_parse_str() in php-proxy/src/Http/Request.php on line 130

Can this please be fixed?

**Comment by Athlon1600** [comment]
Did you install php-proxy-app through composer or did you download a pre-installed version from php-proxy.com? Because that pre-installed version might be out of date, since this specific issue was already fixed almost a month ago:  
https://github.com/Athlon1600/php-proxy/commit/de75904ae05edcfbb918037d234186ce8d39df88

**Comment by desbest** [comment]
I can't install Composer as I'm on shared hosting and my hosting provider doesn't allow it. Can you update the zip file? I couldn't download your script off Packagist.

**Comment by Athlon1600** [comment]
Yes, I'll try to do that over the weekend.

**Comment by Athlon1600** [comment]
Ok, this should be updated now:  
	https://www.php-proxy.com/download/php-proxy.zip

**Comment by desbest** [comment]
Are you sure you've updated the zip file. I'm still getting the same error.

Also when I try to load Twitter I get

Fatal error: Call to undefined function Proxy\mb_eregi_replace() in /home/filtermy/public_html/php-proxy/vendor/athlon1600/php-proxy/src/Html.php on line 21

**Comment by Athlon1600** [comment]
oh, that's because I forgot to remove mb_string functions from Html.php... it's fixed now.

**Comment by desbest** [comment]
I'm receiving
Fatal error: Call to undefined function Proxy\mb_eregi_replace() in /home/filtermy/public_html/php-proxy/vendor/athlon1600/php-proxy/src/Html.php on line 21
when I try to go to twitter.com

I have installed the latest version.

**Comment by Athlon1600** [comment]
That's because I am unable to do a composer installation on my own machine to be later archived into php-proxy.zip, until packagist.org updates itself. Right now it still returns php-proxy latest version as 5.0.1 even though it's 5.0.2 as of 15 minutes ago. We'll just have to wait a bit. I would try installing this tomorrow.

**Comment by desbest** [comment]
Now I'm getting

Fatal error: Call to undefined method Proxy\Event\ProxyEvent::getName() in /home/filtermy/public_html/php-proxy/vendor/athlon1600/php-proxy/src/Plugin/AbstractPlugin.php on line 47

when I load up twitter.com

**Comment by Athlon1600** [comment]
Fixed:  
https://github.com/Athlon1600/php-proxy/commit/12584d6892779c719d26f79bf464e7d9a2b48f88
